[project]
name = 'Secure-Digital-Identity-for-Government-Services'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.citizen-verification]
path = 'contracts/citizen-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.credential-issuance]
path = 'contracts/credential-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy-management]
path = 'contracts/privacy-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-access]
path = 'contracts/service-access.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
